Bring back missing rev block and no more logs
Signed-off-by: Benoit Donneaux <benoit@leastauthority.com>

diff --git a/ansible/files/update-deployment b/ansible/files/update-deployment
--- a/ansible/files/update-deployment
+++ b/ansible/files/update-deployment
@@ -10,6 +10,14 @@ set -o pipefail # exit on any failed command in pipes
 target=${1?"Unknown target"}
 reference=${2-main}
 
+# Read the revision from stdin
+read -s -r -N 40 -t 1 rev || { echo "Could not read the 40 bytes long revision from stdin!"; exit 1; }
+# Sanity check the revision
+if ! [[ ${rev} =~ [0-9a-f]{40} ]]; then
+  echo "Could not parse the 40 bytes long revision from stdin!"
+  exit 1
+fi
+
 # Set some constants for our deployment
 url_user='git'
 url_host='github.com'
